# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-29 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elevationPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launchTime', models.DateTimeField(verbose_name='Launch time')),
                ('launchLatitude', models.FloatField(verbose_name='Launch latitude')),
                ('launchLongitude', models.FloatField(verbose_name='Launch longitude')),
                ('launchAltitude', models.IntegerField(verbose_name='Launch altitude')),
                ('burstTime', models.DateTimeField(null=True, verbose_name='Burst time')),
                ('burstLatitude', models.FloatField(null=True, verbose_name='Burst latitude')),
                ('burstLongitude', models.FloatField(null=True, verbose_name='Burst longitude')),
                ('burstAltitude', models.IntegerField(null=True, verbose_name='Burst altitude')),
                ('landingTime', models.DateTimeField(null=True, verbose_name='Landing time')),
                ('landingLatitude', models.FloatField(null=True, verbose_name='Landing latitude')),
                ('landingLongitude', models.FloatField(null=True, verbose_name='Landing longitude')),
                ('landingAltitude', models.IntegerField(null=True, verbose_name='Landing altitude')),
                ('usingPrediction', models.DateTimeField(null=True, verbose_name='Prediction time')),
                ('ascentRate', models.FloatField(verbose_name='Ascent rate')),
                ('descentRate', models.FloatField(verbose_name='Descent rate')),
                ('hasBeenRun', models.BooleanField(default=False, verbose_name='Has been run')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('pressure', models.FloatField(null=True)),
                ('temperature', models.IntegerField(null=True)),
                ('ugrd', models.FloatField(null=True)),
                ('vgrd', models.FloatField(null=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Predictor.Prediction')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='elevationpoint',
            index_together=set([('latitude', 'longitude')]),
        ),
    ]
