# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0002_remove_prediction_hasbeenrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='usingPrediction',
            field=models.DateTimeField(verbose_name='Prediction time'),
        ),
    ]
