# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0003_auto_20170813_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='launchLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('altitude', models.FloatField(verbose_name='Elevation')),
            ],
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='launchAltitude',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='launchLatitude',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='launchLongitude',
        ),
        migrations.AlterField(
            model_name='elevationpoint',
            name='elevation',
            field=models.FloatField(verbose_name='Elevation'),
        ),
        migrations.AlterField(
            model_name='elevationpoint',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='elevationpoint',
            name='longitude',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='launchPoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Predictor.launchLocation'),
        ),
    ]
